# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel
matrix:
  exclude:
  - r: oldrel
    os: osx
  - r: devel
    os: osx
notifications:
  email:
    on_success: change
    on_failure: change
addons:
  apt:
    packages:
    - libmagic-dev
    - devscripts
brew_packages:
  - libmagic
  - checkbashisms
r_packages:
  - testthat
  - covr
after_success:
  - test "$TRAVIS_R_VERSION_STRING" = "release" && Rscript -e 'covr::codecov()' || true
